log4j.rootLogger=DEBUG, CONSOLE

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} %-5p [%t] %c - %m%n

# Your application
log4j.logger.com.example=DEBUG

# Harness/Split SDK
log4j.logger.io.split=DEBUG
log4j.logger.split.org.apache=DEBUG
